server:
  port: 8082
#
#spring:
#  application:
#    name: content-service
#  cloud:
#    nacos:
#      discovery:
#        server-addr: localhost:8848
#        username: nacos
#        password: nacos
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/content_center?useSSL=false&serverTimezone=UTC
#    username: root
#    password: password
#
#mybatis-plus:
#  mapper-locations: classpath:/mapper/*Mapper.xml
#  type-aliases-package: top.zhu.*.entity
#  configuration:
#    map-underscore-to-camel-case: true
#    cache-enabled: false
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  global-config:
#    db-config:
#      logic-delete-field: true # ????????????(since 3.3.0,????????????2)
#      logic-delete-value: 1 # ??????(??? 1)
#      logic-not-delete-value: 0 # ??????(??? 0)